name: Dispatch
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "starting"
          curl -vv -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN_FOR_EREFERRAL }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/kazuhiko-ohe/eReferral/dispatches" -d '{"event_type": "update"}'
